### ISSUE TITLE
三人麻雀ルール対応

### ISSUE THREAD

**Issue by yuufyu** [yuufyu/mjai#4]
三人麻雀ルールに対応したmjaiサーバ。
### Policy
- 雀魂と同じルールとする
- 四人麻雀用のロジックは消去する(コードを簡潔にするため)

### TODO
- [x] 三人打ち
- [x] 2-8萬を消去
- [x] 抜きドラ動作(北)
- [x] 抜きドラ役
- [ ] 1萬の次牌を9萬にする(https://github.com/yuugata/mjai/blob/3p/lib/mjai/pai.rb#L150)
- [ ] 点数計算(現状、ツモアガリしたときに和了者の点数が4人麻雀と同じ点数加算されてしまう)
- [ ] 抜きドラ後のツモを嶺上判定させる(https://github.com/yuugata/mjai/blob/master/lib/mjai/player.rb#L116)
